# An Introduction to PyTorch functions

### What is Pytorch?
PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab.It is free and open-source software released under the Modified BSD license.

So in this notebook we will be going through the five basic pytorch functions that comes in handy when dealing with any deep learning project.
Before that lets first understand what a Tensor is and how to create it.


### Tensor
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type and torch.Tensor is an alias for the default tensor type (torch.FloatTensor).

The torch package contains data structures for multi-dimensional tensors and mathematical operations over these are defined. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities.
We can use import the torch module and start using the functions provided by it.

Tensor can be created as follows:

In [1]:
# Import torch and other required modules
import torch

Once the torch library is imported we can create tensors and start using its functions

In [2]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In the above example we have created 2D matrix. We can create tensors of other dimensions as well.

So now as we have basic understanding of what tensor is,we will go through following five basic functions that comes in handy when we are dealing with tensors. We will see some of the working examples and also when it breaks.

- torch.mm(mat1,mat2)
- torch.exp(m1)
- torch.numpy() and torch.from_numpy()
- torch.dot()
- torch.flatten()

## 1. torch.mm(input, mat2, out=None) → Tensor

Whenever we are dealing with Deep Learning projects, we often want to do Matrix multiplication and instead of writing the function ourselves pytorch already comes with torch.mm function which can be used. This function peforms a matrix multiplication of two matrices.
If you remember from your school days about the matrix multiplication, If matrix m1 is (n * m) and matrix m2 is (m * p) dimension then resultant matrix is of (n * p) dimension. 

### Parameters:
* input (Tensor) – the first matrix to be multiplied
* mat2 (Tensor) – the second matrix to be multiplied
* out (Tensor, optional) – the output tensor.

In [3]:
# Example 1
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 2)
torch.mm(mat1, mat2)

tensor([[ 2.9220, -0.2876],
        [ 1.3120,  0.5133]])

 So,As you can see from above example matrix1 is of dimension 2X3 and matrix2 is of dimension 3X2 and the resultant matrix is of dimension 2X2 

In [4]:
mat3 = torch.randn(4, 5)
mat4 = torch.randn(5, 4)
torch.mm(mat3, mat4)

tensor([[-1.0310,  1.4918, -0.1310, -1.0442],
        [ 4.6891,  3.7222,  0.1214,  1.8903],
        [ 4.9598,  3.1609, -1.5195, -0.4366],
        [-2.4798, -0.5157,  0.2747, -3.0870]])

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
mat5 = torch.randn(4, 3)
mat6 = torch.randn(5, 4)
torch.mm(mat5, mat6)

In the above example, as matrix multiplication dimension rule doesnt satisfy it throws Runtime Errror.

So next time whenever you want to use matrix multiplication, make use of this function which is very handy.

## 2. torch.exp(input, out=None) → Tensor

Normally when we are dealing with calculating the loss of our model we want to calculate the exponential, then torch.exp() is helpful.
This function returns new tensor with the exponential of the elements of the input tensor.
### Parameters:
* input (Tensor) – the input tensor.
* out (Tensor, optional) – the output tensor

In [ ]:
# Example 1 - working
exp1 = torch.randn(3,4)
exp1

In [ ]:
torch.exp(exp1)

In the above example the exponential function is called for the exp1 matrix which returns the exponential of all elements of tensor.

In [ ]:
# Example 2 - working
exp1 = torch.randn(3,4)
torch.exp(exp1)

In [ ]:
# Example 3 - doesn't works
t = torch.exp(1,2,3)

So next time whenever you want to calculate the exponential of matrix, make use of this function which is very handy.

## 3.torch.numpy() → ndarray & torch.from_numpy(ndarray) → Tensor

Normally when we are dealing with deep learning and using numpy we may want to inter change the tensor to numpy array and viceversa. torch.numpy() is handy function which tensor as numpy array. The tensor and numpy share the same underlying storage. So any changes done to tensor will be reflected in numpy array and viceversa.And other function torch.from_numpy() creates a new tensor from numpy array.

In [ ]:
# Example 1
tensor1 = torch.randn(2,2)
nparray1 = tensor1.numpy()
nparray1

In the above example tensor1 is of type tensor and using the function numpy we can get the relevant numpy array.

In [ ]:
# Example 2
tensor2 = torch.from_numpy(nparray1)
tensor2

In the above example we created a tensor back from numpy array.
So these two functions will be very useful when we are dealing with the numpy and tensor in our project and if we want to convert from one type to another.

In [ ]:
#Example 3 - breaking
tensor3 = torch.from_numpy([1,2])
tensor3

In the above example, if we try to pass other than numpy array it will fail. So make sure you have numpy array which can passed.

So from the functions torch.numpy() and torch.from_numpy() we see that its easier to convert from numpy array to tensor and viceversa.
Certainly these will be very handy when we are dealing with deep learning projects

## 4. torch.dot(input, tensor) → Tensor

Dot product is common functionality that we require whenever we are dealing with deep learning projects. For this, pytorch makes easier to compute by providing the torch.dot() function which returns the dot product of two input tensors.

In [ ]:
# Example 1
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

In [ ]:
# Example 2
torch.dot(torch.tensor([4, 5]), torch.tensor([7, 8]))

In the above examples,we can see the dot product of the two input tensors returned.

In [ ]:
# Example 2 - Not works
torch.dot(torch.tensor([4, 5, 6]), torch.tensor([7, 8]))

The above fails to run and gives exception as the two input tensors should have the same dimensions.

## 5. torch.flatten(input, start_dim=0, end_dim=-1) → Tensor[](http://)

When we are dealing with images in deep learning projects, sometimes we need to flattern the dimension of matrix to single vector, in those situations we can use the tensor.flatten() function. SO this function flattens a contiguous range of dims in a tensor.

Parameters:
* input (Tensor) – the input tensor.
* start_dim (int) – the first dim to flatten
* end_dim (int) – the last dim to flatten

In [ ]:
# Example 1 - working
t = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
torch.flatten(t)

As you can see from the above example, input tensor is of dimension is of 2*3 dimension and flatten function returns flattens and returns 1D dimension tensor.

In [ ]:
# Example 2 - working
torch.flatten(t, start_dim=1)

Explanation about example

In [ ]:
# Example 3 - breaking (when we give invalid dimensions)
torch.flatten(t, start_dim=2)

So from the above examples it's clear that this function comes in handy whenever we want to return flat structure of our tensor and perform operations on it.

## Conclusion

In this notebook we came across 5 important pytorch functions to work with tensors. Along with when the functions can be used, we should keep an eye on the conditions under which they break.
Apart from this pytorch documentation is great resource and we should constantly check those keep ourselves updated.


## Reference Links
You can go through the official Pytorch documentation which is a great resource of such methods with good examples.
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [ ]:
pip install jovian

In [ ]:
import jovian

In [ ]:
jovian.commit()